/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "investments.get": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "investments.index": [],
    "investments.create": [],
    "investments.store": [],
    "investments.show": [
        {
            "name": "investment",
            "required": true
        }
    ],
    "investments.edit": [
        {
            "name": "investment",
            "required": true
        }
    ],
    "investments.update": [
        {
            "name": "investment",
            "required": true
        }
    ],
    "investments.destroy": [
        {
            "name": "investment",
            "required": true
        }
    ],
    "transactions.index": [],
    "transactions.create": [],
    "transactions.store": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
