/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "options.assets": [],
    "options.transaction-types": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "assets.index": [],
    "assets.create": [],
    "assets.store": [],
    "assets.show": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "assets.edit": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "assets.update": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "assets.destroy": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "transactions.index": [],
    "transactions.create": [],
    "transactions.store": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
